# start-prod.ps1 - Full build and startup in production mode
# Fastify backend serves static frontend + API in the same process/port

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$ErrorActionPreference = "Stop"

function Import-EnvFile {
    param([string]$FilePath)

    if (-not (Test-Path $FilePath)) {
        return $false
    }

    foreach ($entry in Get-Content $FilePath) {
        $line = $entry.Trim()
        if (-not $line -or $line.StartsWith('#')) {
            continue
        }

        $line = $line -replace '^export\s+', ''
        $separatorIndex = $line.IndexOf('=')
        if ($separatorIndex -lt 1) {
            continue
        }

        $name = $line.Substring(0, $separatorIndex).Trim()
        $value = $line.Substring($separatorIndex + 1).Trim()

        if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
            $value = $value.Substring(1, $value.Length - 2)
        }

        [System.Environment]::SetEnvironmentVariable($name, $value, 'Process')
    }

    return $true
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  MONITOR-RPA - Production Build" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# [1/5] Load environment variables from common files
Write-Host "[1/5] Loading environment variables..." -ForegroundColor Yellow
$envFiles = @(
    "$root\.env",
    "$root\.env.local",
    "$root\.env.production",
    "$root\.env.production.local"
)
$loadedFiles = @()
foreach ($envFile in $envFiles) {
    if (Import-EnvFile -FilePath $envFile) {
        $loadedFiles += (Split-Path -Leaf $envFile)
    }
}

if ($loadedFiles.Count -gt 0) {
    Write-Host ("      Loaded: " + ($loadedFiles -join ', ')) -ForegroundColor Gray
} else {
    Write-Host "WARNING: no .env files found. Expecting DATABASE_URL in shell environment." -ForegroundColor DarkYellow
}

if (-not $env:DATABASE_URL) {
    Write-Host "ERROR: DATABASE_URL is not configured." -ForegroundColor Red
    Write-Host "Create .env/.env.local or set DATABASE_URL before running start-prod.ps1." -ForegroundColor Red
    exit 1
}

# Force relative API path for frontend bundle
"# Auto-generated by start-prod.ps1 - do not edit manually`nVITE_API_URL=`n" | `
    Out-File -FilePath "$root\.env.production.local" -Encoding ascii
Write-Host "      VITE_API_URL='' (relative paths)" -ForegroundColor Gray

# [2/5] Frontend build
Write-Host "[2/5] Building frontend (Vite)..." -ForegroundColor Yellow
Set-Location $root
npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: frontend build failed." -ForegroundColor Red
    exit 1
}
Write-Host "      dist/ generated successfully." -ForegroundColor Gray

# [3/5] Backend build
Write-Host "[3/5] Building backend (TypeScript)..." -ForegroundColor Yellow
Set-Location "$root\back-server"
npm run build
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: backend build failed." -ForegroundColor Red
    exit 1
}
Write-Host "      back-server/dist/server.js generated." -ForegroundColor Gray

# [4/5] Database migration
Write-Host "[4/5] Running database migration..." -ForegroundColor Yellow
node "$root\back-server\dist\migrate.js"
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: migration failed. Check DATABASE_URL." -ForegroundColor Red
    exit 1
}
Write-Host "      Database ready." -ForegroundColor Gray

# [5/5] Start server
Write-Host "[5/5] Starting server..." -ForegroundColor Yellow
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Open: http://localhost:8000" -ForegroundColor Green
Write-Host "  Frontend + API in one process" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""

node "$root\back-server\dist\server.js"
