#!/usr/bin/env bash
# start-prod.sh - Full build and startup in production mode (macOS/Linux)
# Fastify backend serves static frontend + API in the same process/port

set -e
root="$(cd "$(dirname "$0")" && pwd)"

load_env_file() {
    local file_path="$1"
    [ -f "$file_path" ] || return 1

    set -o allexport
    # shellcheck disable=SC1090
    source "$file_path"
    set +o allexport
    return 0
}

echo "========================================"
echo "  MONITOR-RPA - Production Build"
echo "========================================"
echo ""

# [1/5] Load environment variables from common files
echo "[1/5] Loading environment variables..."
loaded_files=()
for env_file in \
    "$root/.env" \
    "$root/.env.local" \
    "$root/.env.production" \
    "$root/.env.production.local"
do
    if load_env_file "$env_file"; then
        loaded_files+=("$(basename "$env_file")")
    fi
done

if [ "${#loaded_files[@]}" -gt 0 ]; then
    echo "      Loaded: ${loaded_files[*]}"
else
    echo "WARNING: no .env files found. Expecting DATABASE_URL in shell environment."
fi

if [ -z "${DATABASE_URL:-}" ]; then
    echo "ERROR: DATABASE_URL is not configured."
    echo "Create .env/.env.local or set DATABASE_URL before running start-prod.sh."
    exit 1
fi

# Force relative API path for frontend bundle
printf "# Auto-generated by start-prod.sh - do not edit manually\nVITE_API_URL=\n" \
    > "$root/.env.production.local"
echo "      VITE_API_URL='' (relative paths)"

# [2/5] Frontend build
echo "[2/5] Building frontend (Vite)..."
cd "$root"
npm run build
echo "      dist/ generated successfully."

# [3/5] Backend build
echo "[3/5] Building backend (TypeScript)..."
cd "$root/back-server"
npm run build
echo "      back-server/dist/server.js generated."

# [4/5] Database migration
echo "[4/5] Running database migration..."
node "$root/back-server/dist/migrate.js"
echo "      Database ready."

# [5/5] Start server
echo "[5/5] Starting server..."
echo ""
echo "========================================"
echo "  Open: http://localhost:8000"
echo "  Frontend + API in one process"
echo "========================================"
echo ""

node "$root/back-server/dist/server.js"
